### ISSUE TITLE
Win11 Dirty SRUM State

### ISSUE THREAD

**Issue by 4n6Nk18** [AndrewRathbun/DFIRArtifactMuseum#10]
Hi,

i checked the status of windows11 dirty srudb.dat -> according to the libesedb documents and Windows Esentutl, the database is clean and not dirty. Have i missed anything or is this a clean SRUM Database and incorrect RepoName?

Path to Repo:
(https://github.com/AndrewRathbun/DFIRArtifactMuseum/tree/main/Windows/SRUM/Win11/RathbunVM/Dirty)

libesedb states:
https://github.com/libyal/libesedb/blob/main/documentation/Extensible%20Storage%20Engine%20(ESE)%20Database%20File%20(EDB)%20format.asciidoc#database_state

![dirty srum](https://user-images.githubusercontent.com/59082624/178783879-96594ca6-29ef-4c62-b052-71579da34667.png)

**Comment by AndrewRathbun** [comment]
I will generate new artifacts this weekend to correct this issue. Thank you for bringing it up!

**Comment by AndrewRathbun** [comment]
@4n6Nk18 do you mind checking this repo that just went public to see if any of those artifacts solve this Issue? If so, I'll just move them over.

https://github.com/AndrewRathbun/SANSGoldPaperResearch_FOR500_Rathbun

**Comment by 4n6Nk18** [comment]
Hi, i can check the repo (related to SRUM) @AndrewRathbun

**Comment by 4n6Nk18** [comment]
Same Problem, the SRUDB.dat is in a clean state (https://github.com/AndrewRathbun/SANSGoldPaperResearch_FOR500_Rathbun/blob/main/SRUM/Win11/SRUM/SRUDB.dat) 

![SRUM Teil2](https://user-images.githubusercontent.com/59082624/179806613-68d955ba-a68a-4c4c-8762-cead34e49472.png)

![Screenshot 2022-07-19 185422](https://user-images.githubusercontent.com/59082624/179806736-8b0b89bb-ac50-475a-8b66-3ea1ae16a3b9.png)

**Comment by AndrewRathbun** [comment]
I verified all the files added with `esentutl.exe /mh srudb.dat` and they showed the proper status for the folders they reside in. Thanks for your patience.

**Comment by 4n6Nk18** [comment]
I checked the new srum file. they look great, now i will close the case - thanks :)

**Comment by AndrewRathbun** [comment]
Awesome, glad to hear! Thank you for reporting back 👍
