### ISSUE TITLE
Readme files for Win7 and Win7SP1 are swapped.

### ISSUE THREAD

**Issue by Nisarg12** [AndrewRathbun/DFIRArtifactMuseum#11]
It seems that readme files and possibly the image reflecting the kernel version information for Prefetch samples are swapped entirely.

**Comment by AndrewRathbun** [comment]
fixed: https://github.com/AndrewRathbun/DFIRArtifactMuseum/commit/44a163a45956dea188938bcc80f5dda04d321722
