### ISSUE TITLE
RDP image cache

### ISSUE THREAD

**Issue by AndrewRathbun** [AndrewRathbun/DFIRArtifactMuseum#18]
### Discussed in https://github.com/AndrewRathbun/DFIRArtifactMuseum/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **iopasscape** February  1, 2023</sup>
Hi there,
Could you add RDP  image cache for Windows please?
Some info here: https://hejelylab.github.io/blog/IRC/RDP-Bitmap-Cache
</div>

**Comment by AndrewRathbun** [comment]
@iopasscape it took me a bit to get this generated, but here's a first round of updates based on your request - https://github.com/AndrewRathbun/DFIRArtifactMuseum/commit/9f216098c4c67ca586c91bdbbc7b229f09c42f4c

**Comment by AndrewRathbun** [comment]
@iopasscape this is done

https://github.com/AndrewRathbun/DFIRArtifactMuseum/commit/fcbd155d70c065385a67c256c0ba4f1f3f6c85ee

**Comment by iopasscape** [comment]
Awesome, that's what I was looking for. Thank you very much.
