### ISSUE TITLE
redistribution with license violation and lack of attribution

### ISSUE THREAD

**Issue by joachimmetz** [AndrewRathbun/DFIRArtifactMuseum#2]
This project redistributes the work of others such as https://digitalcorpora.org/ without explicitly mentioning them or the license of the original material. 

https://en.wikipedia.org/wiki/Citation

**Comment by joachimmetz** [comment]
E.g. `All of the disk images, memory dumps, and network packet captures available on this website are freely available and may be used without prior authorization or IRB approval.` so that looks like the data is public domain https://en.wikipedia.org/wiki/Public_domain, but this project redistributes this as MIT

also:

```
Citing the corpora
If you are writing a research article in which you are using data from this cite, please cite our paper:
```

and it would be good to see article here in the broadest sense

**Comment by AndrewRathbun** [comment]
Attribution is of the utmost for this project and is currently a work in progress. Believe me, everything will be properly attributed to their source from which they came. 

The artifacts from the images hosted on Digital Corpora were from Josh Hickman, who is a friend and coworker, and were posted with his explicit permission prior to this repository's creation. READMEs are still being fleshed out for all artifacts, folders, etc and this repository is and will be a work in progress.

**Comment by joachimmetz** [comment]
> The artifacts from the images hosted on Digital Corpora were from Josh Hickman, who is a friend and coworker, and were posted with his explicit permission prior to this repository's creation.

then mention that in your attribution documentation, permission granted to re-license 

better yet, have him contribute the files directly to the project, so that is clear that the "author" re-authoring the files under a different license 

> READMEs are still being fleshed out for all artifacts, folders, etc and this repository is and will be a work in progress.

it is essential to do this before publication

**Comment by joachimmetz** [comment]
@AndrewRathbun you closed it but did not fix it, this repo is now tainted in the sense it is not clear which license should apply to these files. If you downloaded the data from https://digitalcorpora.org/ you agreed to the public domain license and should adhere to it.

**Comment by AndrewRathbun** [comment]
It'll get fixed this weekend. I acknowledge the above. The issue is closed.
