### ISSUE TITLE
Request to update kernel version info for prefetch artifacts.

### ISSUE THREAD

**Issue by Nisarg12** [AndrewRathbun/DFIRArtifactMuseum#9]
Opening this issue in reference to what we discussed on discord, as a reminder for you to update, at your own time, the README.md for prefetch for every OS you collected the samples from.

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/176808570-37a2c160-3caa-46a8-8416-a14283553048.png)

**Comment by AndrewRathbun** [comment]
![image](https://user-images.githubusercontent.com/36825567/176808967-b58c26c0-ea3d-44ca-bb1a-d7fabb395e4c.png)

**Comment by AndrewRathbun** [comment]
Windows 8.1 Pro without update

![image](https://user-images.githubusercontent.com/36825567/176809160-dc92f7a8-b0f2-4a1b-9464-e7ddf4d345c5.png)

**Comment by AndrewRathbun** [comment]
https://github.com/AndrewRathbun/DFIRArtifactMuseum/tree/main/Windows/Prefetch/Win10/APTSimulatorVM

This image can be downloaded here: https://github.com/AndrewRathbun/DFIRArtifactMuseum/tree/main/Windows/!Images#aptsimulatorvm

Same OS/VM for all the images. I just snapshotted back to a certain point, installed a different AV, and made the image.

**Comment by AndrewRathbun** [comment]
I think I nuked the rest of my VMs. If you want, I can generate new ones and ensure I provide this information. This is what the DFIRArtifactMuseum is all about and I want to make sure we get it right. Let me know @Nisarg12 whenever you get a chance!

**Comment by Nisarg12** [comment]
> I think I nuked the rest of my VMs. If you want, I can generate new ones and ensure I provide this information. This is what the DFIRArtifactMuseum is all about and I want to make sure we get it right. Let me know @Nisarg12 whenever you get a chance!
Yes, it'd be nice to redo the prefetch files for all versions but this time with kernel information. The current ones are sufficient by themselves but I'm researching on some unknown values concerned with original file path of executable and potentially partial process tree structures in the prefetch file structure to identify them and help the libscaa document in any way possible.
Let me know if you need help generating the samples as well!

**Comment by AndrewRathbun** [comment]
@Nisarg12 

https://github.com/AndrewRathbun/DFIRArtifactMuseum/tree/main/Windows/Prefetch/Win10/RathbunVM

How does this look so far? I plan to rinse and repeat this for all the versions. Hopefully this will help!

**Comment by AndrewRathbun** [comment]
@Nisarg12 check out all the Prefetch folders now. If you're pleased with the current status, please close this issue. Let me know if I need to do more for you on this! Cheers!

**Comment by Nisarg12** [comment]
> @Nisarg12 check out all the Prefetch folders now. If you're pleased with the current status, please close this issue. Let me know if I need to do more for you on this! Cheers!

It looks perfect, thank you for this!
